name: Blog Post Workflow
on: 
    schedule:
        - cron: '0 * * * *'
jobs: 
    update-readme-with-blog: 
        name: Update this repo's README with latest blog posts
        runs-on: ubuntu-latest
        steps: 
            - uses: actions/checkout@v3
            - uses: gautamkrishnar/blog-post-workflow@1.8.1
              with: 
                max_post_count: "10"
                feed_list: "https://dev.to/feed/hyfydistro , https://hyfydistro.medium.com/feed"
